### ISSUE TITLE
p0f-socket is missing

### ISSUE THREAD

**Issue by projectlinker** [ValdikSS/p0f-mtu#3]
Hello, can you help me, please?
I've installed your script on my server and I've tried to run it with such command  `./p0f-client /opt/p0f-mtu/p0f-socket <ip_adress>` but getting such error

```
[-] SYSTEM ERROR : Can't connect to API socket.
        Location : main(), p0f-client.c:128
      OS message : No such file or directory
```

also, I've tried "p0f-mtu-script" source code and all I get is 
`
PTR test      = Probably home user
Fingerprint and OS match. No proxy detected (this test does not include headers detection).
No OpenVPN detected.
`
but nothing about Detected OS

**Comment by ValdikSS** [comment]
You need to run p0f server first.

**Comment by projectlinker** [comment]
Thank you for your response!
I'm really sorry for such stupid questions, I'm preatty new to all this stuff, can you also guid me with command or step-by-step guide, please?

UPD.
I ran `p0f -Q /opt/p0f-mtu/p0f-socket` but now I'm getting new error:
```
./p0f-client /opt/p0f-mtu/p0f-socket <ip_adress>
[-] PROGRAM ABORT : Short read from API socket.
         Location : main(), p0f-client.c:134
```

**Comment by ValdikSS** [comment]
First run
`./p0f -i eth0 -s p0f-socket -u daemon -d 'tcp and (dst port 80 or src port 80)'`
Where `eth0` is the network interface name.
Then use client to get the data:
`./tools/p0f-client ./p0f-socket 1.2.3.4`
Where `1.2.3.4` — IP address of the client.

**Comment by projectlinker** [comment]
Thank you for your help, but I still getting error message:(
That is what I get when trying to run this command from root directory:
```
p0f -i eth0 -s p0f-socket -u daemon -d 'tcp and (dst port 80 or src port 80)'
[-] ERROR: -s and -i are mutually exclusive.
```
maybe that because flag **-s** is responsible for "read packets from tcpdump snapshot;" and flag **-Q** now responsible for "listen on a specified local stream socket".

Then I've tried something like this (with flag **-o** because **-d** requires **-o.**):
```
p0f -i eth0 -Q /opt/p0f-mtu/p0f-socket -u daemon -d 'tcp and (dst port 443 or src port 443)' -o p0f.log
p0f - passive os fingerprinting utility, version 2.0.8
(C) M. Zalewski <lcamtuf@dione.cc>, W. Stearns <wstearns@pobox.com>
p0f: listening (SYN) on 'eth0', 262 sigs (14 generic, cksum 0F1F5CA2), rule: 'tcp and (dst port 443 or src port 443)'.
[*] Accepting queries at socket /opt/p0f-mtu/p0f-socket (timeout: 2 s).
```
and after that, as you said:
```
./opt/p0f-mtu/tools/p0f-client /opt/p0f-mtu/p0f-socket <IP_adress>
[-] PROGRAM ABORT : Short read from API socket.
         Location : main(), p0f-client.c:134
```

**Comment by projectlinker** [comment]
I've found my problem, but when I'm typing my ip adress in the terminal I can see all the information needed (MTU, OS Details, etc). But when I try to exec it with php on my website with `$_SERVER['REMOTE_ADDR']` all I get is  `No matching host in p0f cache. That's all we know.`.
I'm using DigitalOcean,  SreverPilot and Cloudflare.
What's wrong, can you tell me, please?

**Comment by ValdikSS** [comment]
You can't use CloudFlare caching. p0f needs to capture raw packet data from the original IP address. Using CloudFlare as a proxy will not deliver necessary data because it's a proxy and is not designed to save TCP stack features, and it would send packets from CloudFlare IP addresses which is also incompatible with p0f.

**Comment by projectlinker** [comment]
Thank you very much for your time and help!!!
