### ISSUE TITLE
i have lots of traffic need check os, please help me

### ISSUE THREAD

**Issue by xufeng** [ValdikSS/p0f-mtu#4]
i'm new.

thanks your script. very useful.

i use your p0f-mtu-script on my website.

i see this:
[+] Listening on API socket 'p0f-socket' (max 20 clients).

but i have 1 million users/per day on my website,  how can i do ?

**Comment by xufeng** [comment]
i use **-s 100** in command

./p0f -i eth0 -s p0f-socket -u **-S 100** daemon -d 'tcp and (dst port 80 or src port 80)'

> [+] Listening on API socket 'p0f-socket' (max 100 clients).

but 100 Not enough，  i need 1000 user , please help me.


can i need Modify p0f source code ? how can i do it ?

i hope p0f High concurrence like nginx.
please help me.

**Comment by ValdikSS** [comment]
p0f (and capturing with libpcap in general) is not suitable for high bandwidth resources.
There's no legitimate reason to use p0f on a website with million users per day. You're doing something wrong.
